version: '3.5'

services:
  reactjs:
    container_name: reactjs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'd:/docker/context/reactapp:/home/reactapp'
      - 'd:/docker/context/node_modules:/home/reactapp/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
